/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConfirmacaoPresencaCL;
import Negocio.ConfirmacaoPresencaBO;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronaima
 */
public class ConfirmacaoPresencaUI extends javax.swing.JFrame {
    public static synchronized ConfirmacaoPresencaUI getInstance(){
        ConfirmacaoPresencaUI confirmacaoPresencaInstancia = null;
        if(confirmacaoPresencaInstancia == null){
            confirmacaoPresencaInstancia = new ConfirmacaoPresencaUI();
            confirmacaoPresencaInstancia.setLocationRelativeTo(null);
        }
        return confirmacaoPresencaInstancia;
    }

    /**
     * Creates new form ConfirmacaoPresencaUI
     */
    public ConfirmacaoPresencaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoEvento = new javax.swing.JTextField();
        txtRaAluno = new javax.swing.JTextField();
        btnConfirmarPresenca = new javax.swing.JButton();
        txtCodConfirmacaoPresenca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConfirmacaoPresenca = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Cod Cnfirmação Presença:");

        jLabel2.setText("Codigo Evento:");

        jLabel3.setText("Ra Aluno:");

        txtCodigoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoEventoActionPerformed(evt);
            }
        });

        txtRaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRaAlunoActionPerformed(evt);
            }
        });

        btnConfirmarPresenca.setText("Confirmar Presença");
        btnConfirmarPresenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPresencaActionPerformed(evt);
            }
        });

        txtCodConfirmacaoPresenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodConfirmacaoPresencaActionPerformed(evt);
            }
        });

        tblConfirmacaoPresenca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Confirmação Presença", "Código Evento", "RA Aluno"
            }
        ));
        tblConfirmacaoPresenca.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblConfirmacaoPresencaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblConfirmacaoPresenca);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(txtCodConfirmacaoPresenca, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(4, 4, 4)
                            .addComponent(txtCodigoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(2, 2, 2)
                            .addComponent(txtRaAluno)))
                    .addComponent(btnConfirmarPresenca)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodConfirmacaoPresenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmarPresenca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRaAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRaAlunoActionPerformed

    private void txtCodigoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEventoActionPerformed

    private void btnConfirmarPresencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPresencaActionPerformed
        ConfirmacaoPresencaBO confirmacaoPresenca = null;
        try {
            confirmacaoPresenca = readConfirmacaoPresenca();
        } catch (ParseException ex) {
            Logger.getLogger(EventoUIii.class.getName()).log(Level.SEVERE, null, ex);
        }
        ConfirmacaoPresencaCL.newConfirmacaoPresenca(confirmacaoPresenca);
        JOptionPane.showMessageDialog(null,"Evento cadastrado com sucesso!");
        retrieveConfirmacaoPresenca();
        txtCodConfirmacaoPresenca.setText("");
        txtCodigoEvento.setText("");
        txtRaAluno.setText("");
    }//GEN-LAST:event_btnConfirmarPresencaActionPerformed

    private void txtCodConfirmacaoPresencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodConfirmacaoPresencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodConfirmacaoPresencaActionPerformed

    private void tblConfirmacaoPresencaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblConfirmacaoPresencaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblConfirmacaoPresencaAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmacaoPresencaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmacaoPresencaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmacaoPresencaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmacaoPresencaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmacaoPresencaUI().setVisible(true);
            }
        });
    }
    
    
    public ConfirmacaoPresencaBO readConfirmacaoPresenca() throws ParseException{
        
        String codigo = txtCodConfirmacaoPresenca.getText();
            int Cod = Integer.parseInt(codigo);
           
        String ra = txtRaAluno.getText();
            int RA = Integer.parseInt(ra);
        
        String CodigoEvento = txtCodigoEvento.getText();
            int codigoEvento = Integer.parseInt(CodigoEvento);
            
             
        return new ConfirmacaoPresencaBO(codigoEvento, RA, Cod );
    }    

    public void findConfirmacaoPresenca(ConfirmacaoPresencaBO c){
        txtCodigoEvento.setText(String.valueOf(c.getCodigoEvento()));
        txtCodConfirmacaoPresenca.setText(String.valueOf(c.getCod()));
        txtRaAluno.setText(String.valueOf(c.getRA()));
    }  
    
    public void retrieveConfirmacaoPresenca(){
        DefaultTableModel modelinho = new DefaultTableModel();
        modelinho.addColumn("Codigo Evento");
        modelinho.addColumn("Codigo de Confirmação de Presença");
        modelinho.addColumn("RA do aluno");

        tblConfirmacaoPresenca.setModel(modelinho);        

        ConfirmacaoPresencaCL.showConfirmacaoPresenca().stream().forEach((c) -> {                
            modelinho.addRow(new Object[]{
                c.getCodigoEvento(),
                c.getCod(),
                c.getRA()
            });
        });
        tblConfirmacaoPresenca.setModel(modelinho);
    }

    private void writeConfirmacaoPresenca(ConfirmacaoPresencaBO c){
        
        txtCodigoEvento.setText(String.valueOf(c.getCodEvento()));
        txtCodConfirmacaoPresenca.setText(String.valueOf(c.getCodEvento()));
        txtRaAluno.setText(String.valueOf(c.getCodEvento()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarPresenca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblConfirmacaoPresenca;
    private javax.swing.JTextField txtCodConfirmacaoPresenca;
    private javax.swing.JTextField txtCodigoEvento;
    private javax.swing.JTextField txtRaAluno;
    // End of variables declaration//GEN-END:variables
}
