/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.EventoCL;
import Controle.PalestraEventoCL;
import Negocio.EventoBO;

import Negocio.PalestraEventoBO;
import java.text.Format;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronaima
 */
public class EventoUIii extends javax.swing.JFrame {
        
    private static EventoUIii eventoInstancia; 
    /**
     * Creates new form EventoUI
     */
    public EventoUIii() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigoEvento = new javax.swing.JLabel();
        lblNomeEvento = new javax.swing.JLabel();
        lblDescricaoEvento = new javax.swing.JLabel();
        lblDataInicioInscricaoEvento = new javax.swing.JLabel();
        lblDataFimInscricaoEvento = new javax.swing.JLabel();
        lblDataInicioEvento = new javax.swing.JLabel();
        lblDataFimEvento = new javax.swing.JLabel();
        lblDataFimPublicacaoEvento = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtCodigoEvento = new javax.swing.JTextField();
        txtNomeEvento = new javax.swing.JTextField();
        txtDescricaoEvento = new javax.swing.JTextField();
        txtDataInicioInscricaoEvento = new javax.swing.JTextField();
        txtDataFimInscricaoEvento = new javax.swing.JTextField();
        txtDataInicioEvento = new javax.swing.JTextField();
        txtDataFimEvento = new javax.swing.JTextField();
        txtDataFimPublicacaoEvento = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvento = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCodPalestrante1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodPalestrante2 = new javax.swing.JTextField();
        txtCodPalestrante3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Eventos");
        setResizable(false);

        lblCodigoEvento.setText("Codigo Evento:");
        lblCodigoEvento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblCodigoEventoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblNomeEvento.setText("Nome Evento:");
        lblNomeEvento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblNomeEventoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblDescricaoEvento.setText("Descrição Evento:");
        lblDescricaoEvento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblDescricaoEventoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblDataInicioInscricaoEvento.setText("Data de Inicio Inscricao Evento:");
        lblDataInicioInscricaoEvento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblDataInicioInscricaoEventoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblDataFimInscricaoEvento.setText("Data Fim Inscricao Evento:");
        lblDataFimInscricaoEvento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblDataFimInscricaoEventoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblDataInicioEvento.setText("Data Inicio Evento:");
        lblDataInicioEvento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblDataInicioEventoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblDataFimEvento.setText("Data Fim Evento:");
        lblDataFimEvento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblDataFimEventoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblDataFimPublicacaoEvento.setText("Data Fim Publicacao Evento:");
        lblDataFimPublicacaoEvento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblDataFimPublicacaoEventoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblStatus.setText("Status:");
        lblStatus.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblStatusAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtCodigoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoEventoActionPerformed(evt);
            }
        });

        txtNomeEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEventoActionPerformed(evt);
            }
        });

        txtDescricaoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoEventoActionPerformed(evt);
            }
        });

        txtDataInicioInscricaoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataInicioInscricaoEventoActionPerformed(evt);
            }
        });

        txtDataFimInscricaoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataFimInscricaoEventoActionPerformed(evt);
            }
        });

        txtDataInicioEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataInicioEventoActionPerformed(evt);
            }
        });

        txtDataFimEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataFimEventoActionPerformed(evt);
            }
        });

        txtDataFimPublicacaoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataFimPublicacaoEventoActionPerformed(evt);
            }
        });

        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pequisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        tblEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEvento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblEventoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblEvento);

        jLabel1.setText("Codigo Palesta 1:");

        txtCodPalestrante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodPalestrante1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo Palesta 2:");

        jLabel3.setText("Codigo Palesta 3:");

        txtCodPalestrante2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodPalestrante2ActionPerformed(evt);
            }
        });

        txtCodPalestrante3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodPalestrante3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(222, 222, 222))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigoEvento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeEvento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDescricaoEvento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescricaoEvento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataInicioInscricaoEvento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataInicioInscricaoEvento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataFimInscricaoEvento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataFimInscricaoEvento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataInicioEvento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataInicioEvento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataFimEvento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataFimEvento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataFimPublicacaoEvento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataFimPublicacaoEvento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStatus)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtCodPalestrante1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodPalestrante2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodPalestrante3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoEvento)
                    .addComponent(txtCodigoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodPalestrante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEvento)
                    .addComponent(txtNomeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodPalestrante2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricaoEvento)
                    .addComponent(txtDescricaoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodPalestrante3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataInicioInscricaoEvento)
                    .addComponent(txtDataInicioInscricaoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataFimInscricaoEvento)
                    .addComponent(txtDataFimInscricaoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataInicioEvento)
                    .addComponent(txtDataInicioEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataFimEvento)
                    .addComponent(txtDataFimEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataFimPublicacaoEvento)
                    .addComponent(txtDataFimPublicacaoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static synchronized EventoUIii getInstance(){
        if(eventoInstancia == null){
            eventoInstancia = new EventoUIii();
        }
        // Abrir janela centralizada.
        eventoInstancia.setLocationRelativeTo(null);
        
        return eventoInstancia;
    }
    
    private void txtCodigoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEventoActionPerformed

    private void lblCodigoEventoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblCodigoEventoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCodigoEventoAncestorAdded

    private void lblNomeEventoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblNomeEventoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNomeEventoAncestorAdded

    private void lblDescricaoEventoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblDescricaoEventoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDescricaoEventoAncestorAdded

    private void lblDataInicioInscricaoEventoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblDataInicioInscricaoEventoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDataInicioInscricaoEventoAncestorAdded

    private void lblDataFimInscricaoEventoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblDataFimInscricaoEventoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDataFimInscricaoEventoAncestorAdded

    private void lblDataInicioEventoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblDataInicioEventoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDataInicioEventoAncestorAdded

    private void lblDataFimEventoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblDataFimEventoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDataFimEventoAncestorAdded

    private void lblDataFimPublicacaoEventoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblDataFimPublicacaoEventoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDataFimPublicacaoEventoAncestorAdded

    private void lblStatusAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblStatusAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblStatusAncestorAdded

    private void txtNomeEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEventoActionPerformed

    private void txtDescricaoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoEventoActionPerformed

    private void txtDataFimInscricaoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataFimInscricaoEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFimInscricaoEventoActionPerformed

    private void txtDataInicioEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataInicioEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataInicioEventoActionPerformed

    private void txtDataFimEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataFimEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFimEventoActionPerformed

    private void txtDataFimPublicacaoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataFimPublicacaoEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFimPublicacaoEventoActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void tblEventoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblEventoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEventoAncestorAdded

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        PalestraEventoBO palestraEvento = null;
        try {
            palestraEvento = readPalestraEvento();
        } catch (ParseException ex) {
            Logger.getLogger(EventoUIii.class.getName()).log(Level.SEVERE, null, ex);
        }
        PalestraEventoCL.newPalestraEvento(palestraEvento);
        JOptionPane.showMessageDialog(null,"Evento cadastrado com sucesso!");
        retrievePalestraEvento();// TODO add your handling code here:
        txtCodPalestrante1.setText("");
        txtCodPalestrante2.setText("");
        txtCodPalestrante3.setText("");
        txtCodigoEvento.setText("");
        txtDataFimEvento.setText("");
        txtDataFimInscricaoEvento.setText("");
        txtDataFimPublicacaoEvento.setText("");
        txtDataInicioEvento.setText("");
        txtDataInicioInscricaoEvento.setText("");
        txtDescricaoEvento.setText("");
        txtNomeEvento.setText("");
        txtStatus.setText("");
       
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        PalestraEventoBO evento = null;
        try {
            evento = readPalestraEvento();
        } catch (ParseException ex) {
            Logger.getLogger(EventoUIii.class.getName()).log(Level.SEVERE, null, ex);
        }
        PalestraEventoCL.updatePalestraEvento(evento);
        JOptionPane.showMessageDialog(null,"Evento atualizado com sucesso!");
        retrievePalestraEvento();
        
        txtCodPalestrante1.setText("");
        txtCodPalestrante2.setText("");
        txtCodPalestrante3.setText("");
        txtCodigoEvento.setText("");
        txtDataFimEvento.setText("");
        txtDataFimInscricaoEvento.setText("");
        txtDataFimPublicacaoEvento.setText("");
        txtDataInicioEvento.setText("");
        txtDataInicioInscricaoEvento.setText("");
        txtDescricaoEvento.setText("");
        txtNomeEvento.setText("");
        txtStatus.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int codigo = Integer.parseInt(txtCodigoEvento.getText());
        PalestraEventoCL.deletePalestraEvento(codigo);
        retrievePalestraEvento();
        
        txtCodPalestrante1.setText("");
        txtCodPalestrante2.setText("");
        txtCodPalestrante3.setText("");
        txtCodigoEvento.setText("");
        txtDataFimEvento.setText("");
        txtDataFimInscricaoEvento.setText("");
        txtDataFimPublicacaoEvento.setText("");
        txtDataInicioEvento.setText("");
        txtDataInicioInscricaoEvento.setText("");
        txtDescricaoEvento.setText("");
        txtNomeEvento.setText("");
        txtStatus.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        int     cod = Integer.parseInt(txtCodigoEvento.getText());
//        double  rend = Double.parseDouble(txtRenda.getText());
        String  nom = txtNomeEvento.getText();
        
        if(nom != null){
            PalestraEventoBO c = PalestraEventoCL.findPalestraEventoNome(nom);
            findPalestraEvento(c);
        }else if(String.valueOf(cod) != null){
            
            String str = String.valueOf(cod);
            // suppose str becomes null after some operation(s).
            int number = 0;
            try
            {
                if(str != null)
                  number = Integer.parseInt(str);
            }
            catch (NumberFormatException e)
            {
                number = 0;
            }            
            
            PalestraEventoBO c = PalestraEventoCL.findPalestraEventoCod(number);
            findPalestraEvento(c);
        }else{
            JOptionPane.showMessageDialog(null,"Digite um parâmetro válido!");
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtCodPalestrante2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodPalestrante2ActionPerformed
        //implementar para puxar o palestrante por codigo
    }//GEN-LAST:event_txtCodPalestrante2ActionPerformed

    private void txtCodPalestrante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodPalestrante1ActionPerformed
        //implementar para puxar o palestrante por codigo
    }//GEN-LAST:event_txtCodPalestrante1ActionPerformed

    private void txtCodPalestrante3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodPalestrante3ActionPerformed
        //implementar para puxar o palestrante por codigo
    }//GEN-LAST:event_txtCodPalestrante3ActionPerformed

    private void txtDataInicioInscricaoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataInicioInscricaoEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataInicioInscricaoEventoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventoUIii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventoUIii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventoUIii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventoUIii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventoUIii().setVisible(true);
            }
        });
    }
    
    public PalestraEventoBO readPalestraEvento() throws ParseException{
        
        String codigo = txtCodigoEvento.getText();
            int codEvento = Integer.parseInt(codigo);
            
        String nomeEvento = txtNomeEvento.getText();
        
        String descricaoEvento = txtDescricaoEvento.getText();
        
        String dataInicioInscricaoDeEvento = txtDataInicioInscricaoEvento.getText();
            SimpleDateFormat diie = new SimpleDateFormat("dd/MM/yyyy");
            diie.setLenient(false);
            Date dataInicioInscricaoEvento = diie.parse(dataInicioInscricaoDeEvento);            
        String dataFimInscricaoDeEvento = txtDataFimInscricaoEvento.getText();
            SimpleDateFormat dfie = new SimpleDateFormat("dd/MM/yyyy");
            dfie.setLenient(false);
            Date dataFimInscricaoEvento= dfie.parse(dataFimInscricaoDeEvento);            
        String dataInicioDeEvento = txtDataInicioEvento.getText();
            SimpleDateFormat die = new SimpleDateFormat("dd/MM/yyyy");
            die.setLenient(false);
            Date dataInicioEvento = die.parse(dataInicioDeEvento);
        String dataFimDeEvento = txtDataFimEvento.getText();
            SimpleDateFormat dfe = new SimpleDateFormat("dd/MM/yyyy");
            dfe.setLenient(false);
            Date dataFimEvento = dfe.parse(dataFimDeEvento);
        String dataFimPublicacaoDeEvento = txtDataFimPublicacaoEvento.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false);
            Date dataFimPublicacaoEvento = sdf.parse(dataFimPublicacaoDeEvento);
            
        String status = txtStatus.getText();
        
        String codigo1 = txtCodPalestrante1.getText();
            int codPalestra1 = Integer.parseInt(codigo1);
            
        String codigo2 = txtCodPalestrante2.getText();
            int codPalestra2 = Integer.parseInt(codigo2);
            
        String codigo3 = txtCodPalestrante3.getText();
            int codPalestra3 = Integer.parseInt(codigo3);
        
        return new PalestraEventoBO(codEvento, nomeEvento, descricaoEvento, dataInicioInscricaoEvento, dataFimInscricaoEvento, dataInicioEvento, dataFimEvento, dataFimPublicacaoEvento, status, codPalestra1,codPalestra2, codPalestra3 );
    }    

    public void findPalestraEvento(PalestraEventoBO c){
        txtCodigoEvento.setText(String.valueOf(c.getCodEvento()));
        txtNomeEvento.setText(c.getNomeEvento());        
        txtDescricaoEvento.setText(c.getDescricaoEvento());
        SimpleDateFormat diie = new SimpleDateFormat("dd/MM/yyyy");
        txtDataInicioInscricaoEvento.setText(String.valueOf(diie.format(c.getDataInicioInscricaoEvento())));//diie.format(c.getDataInicioInscricaoEvento().toString()))); 
        SimpleDateFormat dfie = new SimpleDateFormat("dd/MM/yyyy");
        txtDataFimInscricaoEvento.setText(String.valueOf(diie.format(c.getDataFimInscricaoEvento())));//dfie.format(c.getDataFimInscricaoEvento().toString()));
        SimpleDateFormat die = new SimpleDateFormat("dd/MM/yyyy");
        txtDataInicioEvento.setText(String.valueOf(diie.format(c.getDataInicioEvento())));//die.format(c.getDataInicioEvento().toString()));  
        SimpleDateFormat dfe = new SimpleDateFormat("dd/MM/yyyy");
        txtDataFimEvento.setText(String.valueOf(diie.format(c.getDataFimEvento())));//dfe.format(c.getDataFimEvento().toString()));  
        SimpleDateFormat dfpe = new SimpleDateFormat("dd/MM/yyyy");
        txtDataFimPublicacaoEvento.setText(String.valueOf(diie.format(c.getDataFimPublicacaoEvento())));//dfpe.format(c.getDataFimPublicacaoEvento().toString()));  
        txtStatus.setText(c.getStatus());  
        txtCodPalestrante1.setText(String.valueOf(c.getCodEvento()));
        txtCodPalestrante2.setText(String.valueOf(c.getCodEvento()));
        txtCodPalestrante3.setText(String.valueOf(c.getCodEvento()));
    }  
    
    public void retrievePalestraEvento(){
            DefaultTableModel modelinho=new DefaultTableModel();
            modelinho.addColumn("Codigo Evento");
            modelinho.addColumn("Nome do Evento");
            modelinho.addColumn("Descrição Evento");
            modelinho.addColumn("Data Inicio Inscricao Evento");
            modelinho.addColumn("Data Fim Inscricao Evento");
            modelinho.addColumn("Data Inicio Evento");
            modelinho.addColumn("Data Fim Evento");
            modelinho.addColumn("Data Fim Publicacao Evento");
            modelinho.addColumn("status");
            modelinho.addColumn("Palestra1");
            modelinho.addColumn("Palestra2");
            modelinho.addColumn("Palestra3");
            
            tblEvento.setModel(modelinho);        
            
            for(PalestraEventoBO c:PalestraEventoCL.showPalestraEvento()){
                
                // Define o formato da data e após aplica mascara para preencher os campos de texto.
                Format formatter = new SimpleDateFormat("dd/MM/yyyy");
                
                String getDataInicioInscricaoEvento = formatter.format(c.getDataInicioInscricaoEvento());
                String getDataFimInscricaoEvento = formatter.format(c.getDataFimInscricaoEvento());
                String getDataInicioEvento = formatter.format(c.getDataInicioEvento());
                String getDataFimEvento = formatter.format(c.getDataFimEvento());
                String getDataFimPublicacaoEvento = formatter.format(c.getDataFimPublicacaoEvento());
                
                modelinho.addRow(new Object[]{
                    c.getCodEvento(),
                    c.getNomeEvento(), 
                    c.getDescricaoEvento(),
                    c.getCodPalestra1(),
                    c.getCodPalestra2(),
                    c.getCodPalestra3(),
                    
                    getDataInicioInscricaoEvento, 
                    getDataFimInscricaoEvento, 
                    getDataInicioEvento, 
                    getDataFimEvento,
                    getDataFimPublicacaoEvento,
                    
                    c.getStatus()
                        
                });
            }
            tblEvento.setModel(modelinho);
    }

    private void writePalestraEvento(PalestraEventoBO c){
        txtNomeEvento.setText(c.getNomeEvento());
        txtCodigoEvento.setText(String.valueOf(c.getCodEvento()));
        txtDescricaoEvento.setText(c.getDescricaoEvento());
        SimpleDateFormat diie = new SimpleDateFormat("dd/MM/yyyy");
        txtDataInicioInscricaoEvento.setText(diie.format(c.getDataInicioInscricaoEvento())); 
        SimpleDateFormat dfie = new SimpleDateFormat("dd/MM/yyyy");
        txtDataFimInscricaoEvento.setText(dfie.format(c.getDataFimInscricaoEvento().toString()));
        SimpleDateFormat die = new SimpleDateFormat("dd/MM/yyyy");
        txtDataInicioEvento.setText(die.format(c.getDataInicioEvento().toString()));  
        SimpleDateFormat dfe = new SimpleDateFormat("dd/MM/yyyy");
        txtDataFimEvento.setText(dfe.format(c.getDataFimEvento().toString()));  
        SimpleDateFormat dfpe = new SimpleDateFormat("dd/MM/yyyy");
        txtDataFimPublicacaoEvento.setText(dfpe.format(c.getDataFimPublicacaoEvento().toString()));  
        txtStatus.setText(c.getStatus()); 
        txtCodPalestrante1.setText(c.getNomeEvento());
        txtCodPalestrante2.setText(c.getNomeEvento());
        txtCodPalestrante3.setText(c.getNomeEvento());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoEvento;
    private javax.swing.JLabel lblDataFimEvento;
    private javax.swing.JLabel lblDataFimInscricaoEvento;
    private javax.swing.JLabel lblDataFimPublicacaoEvento;
    private javax.swing.JLabel lblDataInicioEvento;
    private javax.swing.JLabel lblDataInicioInscricaoEvento;
    private javax.swing.JLabel lblDescricaoEvento;
    private javax.swing.JLabel lblNomeEvento;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblEvento;
    private javax.swing.JTextField txtCodPalestrante1;
    private javax.swing.JTextField txtCodPalestrante2;
    private javax.swing.JTextField txtCodPalestrante3;
    private javax.swing.JTextField txtCodigoEvento;
    private javax.swing.JTextField txtDataFimEvento;
    private javax.swing.JTextField txtDataFimInscricaoEvento;
    private javax.swing.JTextField txtDataFimPublicacaoEvento;
    private javax.swing.JTextField txtDataInicioEvento;
    private javax.swing.JTextField txtDataInicioInscricaoEvento;
    private javax.swing.JTextField txtDescricaoEvento;
    private javax.swing.JTextField txtNomeEvento;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
