/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Controle.PalestranteCL;
import Negocio.PalestranteBO;
import java.text.ParseException;
/**
 *
 * @author ronaima
 */
public class PalestranteUI extends javax.swing.JFrame {
    private javax.swing.JTable tblPalestrante;
    private static PalestranteUI palestranteInstancia; 

    /**
     * Creates new form PalestranteUI
     */
    public PalestranteUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JTable tblPalestrante = new javax.swing.JTable();
        lblCodPalestrante = new javax.swing.JLabel();
        lblNomePalestrante = new javax.swing.JLabel();
        lblMiniCurriculoPalestrante = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtCodPalestrante = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtMiniCurriculoPalestrante = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        tblPalestrante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPalestrante.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblPalestranteAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblPalestrante);

        lblCodPalestrante.setText("Codigo do Palestrante:");
        lblCodPalestrante.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblCodPalestranteAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblNomePalestrante.setText("Nome Palestrante:");
        lblNomePalestrante.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblNomePalestranteAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblMiniCurriculoPalestrante.setText("Mini Curriculo:");
        lblMiniCurriculoPalestrante.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblMiniCurriculoPalestranteAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblEmail.setText("Email:");
        lblEmail.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblEmailAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblTelefone.setText("Telefone:");
        lblTelefone.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblTelefoneAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtCodPalestrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodPalestranteActionPerformed(evt);
            }
        });

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtMiniCurriculoPalestrante.setCursor(new java.awt.Cursor(java.awt.Cursor.NW_RESIZE_CURSOR));
        txtMiniCurriculoPalestrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiniCurriculoPalestranteActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomePalestrante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMiniCurriculoPalestrante)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodPalestrante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodPalestrante, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtMiniCurriculoPalestrante, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodPalestrante)
                    .addComponent(txtCodPalestrante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomePalestrante)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMiniCurriculoPalestrante)
                    .addComponent(txtMiniCurriculoPalestrante, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static synchronized PalestranteUI getInstance(){
        if(palestranteInstancia == null){
            palestranteInstancia = new PalestranteUI();
        }
        palestranteInstancia.setLocationRelativeTo(null);
        return palestranteInstancia;
    }
    
    private void lblCodPalestranteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblCodPalestranteAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCodPalestranteAncestorAdded

    private void lblNomePalestranteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblNomePalestranteAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNomePalestranteAncestorAdded

    private void lblMiniCurriculoPalestranteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblMiniCurriculoPalestranteAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMiniCurriculoPalestranteAncestorAdded

    private void lblEmailAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblEmailAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEmailAncestorAdded

    private void lblTelefoneAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblTelefoneAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTelefoneAncestorAdded

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtMiniCurriculoPalestranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiniCurriculoPalestranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiniCurriculoPalestranteActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCodPalestranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodPalestranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodPalestranteActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        PalestranteBO cliente;
        try {
            cliente = readPalestrante();
            PalestranteCL.newPalestrante(cliente);
            JOptionPane.showMessageDialog(null, "Palestrante cadastrado com sucesso!");
            retrievePalestrante();
            txtCodPalestrante.setText("");
            txtNome.setText("");
            txtMiniCurriculoPalestrante.setText("");
            txtEmail.setText("");
            txtTelefone.setText("");
        } catch (Exception ex) {
        }        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        int     cod = Integer.parseInt(txtCodPalestrante.getText());
//        double  rend = Double.parseDouble(txtRenda.getText());
        String  nom = txtNome.getText();
        
        if(nom != null){
            PalestranteBO c = PalestranteCL.findPalestranteNome(nom);
            findPalestrante(c);
        }else if(String.valueOf(cod) != null){
            
            String str = String.valueOf(cod);
            // suppose str becomes null after some operation(s).
            int number = 0;
            try
            {
                if(str != null)
                  number = Integer.parseInt(str);
            }
            catch (NumberFormatException e)
            {
                number = 0;
            }            
            
            PalestranteBO c = PalestranteCL.findPalestranteCod(number);
            findPalestrante(c);
        }else{
            JOptionPane.showMessageDialog(null,"Digite um parâmetro válido!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        PalestranteBO Palestrante = readPalestrante();
        PalestranteCL.updatePalestrante(Palestrante);
        JOptionPane.showMessageDialog(null,"Palestrante atualizado com sucesso!");
        retrievePalestrante();
    // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int codigo = Integer.parseInt(txtCodPalestrante.getText());
        PalestranteCL.deletePalestrante(codigo);
        retrievePalestrante();// TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tblPalestranteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblPalestranteAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPalestranteAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PalestranteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PalestranteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PalestranteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PalestranteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PalestranteUI().setVisible(true);
            }
        });
    }
    
    public PalestranteBO readPalestrante(){
        
        String nomePalestrante = txtNome.getText();
        String codigo = txtCodPalestrante.getText();
            int codigoPalestrante = Integer.parseInt(codigo);
        String eMail = txtEmail.getText();
        String telefone = txtTelefone.getText();
        String strMiniCurriculo = txtMiniCurriculoPalestrante.getText();
        
        return new PalestranteBO(codigoPalestrante, nomePalestrante, strMiniCurriculo, eMail, telefone);
    }    

    public void findPalestrante(PalestranteBO c){
        txtNome.setText(c.getNomePalestrante());
        txtCodPalestrante.setText(String.valueOf(c.getCodPalestrante()));
        txtEmail.setText(c.geteMail());  
        txtTelefone.setText(c.getTelefone()); 
        txtMiniCurriculoPalestrante.setText(c.getMiniCurriculoPalestrante());
    }  
    
    public void retrievePalestrante(){
        DefaultTableModel modelinho = new DefaultTableModel();

        modelinho.addColumn("Codigo Palestrante");
        modelinho.addColumn("Nome");
        modelinho.addColumn("Mini Curriculo");
        modelinho.addColumn("E-mail");
        modelinho.addColumn("Telefone");

        tblPalestrante.setModel(modelinho);        

        PalestranteCL.showPalestrante().stream().forEach((c) -> {
            modelinho.addRow(new Object[]{
                c.getCodPalestrante(),
                c.getNomePalestrante(),
                c.getMiniCurriculoPalestrante(),
                c.geteMail(), 
                c.getTelefone()
            });
        });
        tblPalestrante.setModel(modelinho);
    }
    
    @SuppressWarnings("unused")
	private void writePalestrante(PalestranteBO c){
        txtNome.setText(c.getNomePalestrante());
        txtCodPalestrante.setText(String.valueOf(c.getCodPalestrante()));
        txtTelefone.setText(c.getTelefone());
        txtEmail.setText(c.geteMail());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodPalestrante;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMiniCurriculoPalestrante;
    private javax.swing.JLabel lblNomePalestrante;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtCodPalestrante;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMiniCurriculoPalestrante;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
