/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.SalaCL;
import Negocio.SalaBO;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronaima
 */
public class SalaUI extends javax.swing.JFrame {
    private static SalaUI salaInstancia; 
    /**
     * Creates new form SalaUI
     */
    public SalaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigoSala = new javax.swing.JLabel();
        lblNomeSala = new javax.swing.JLabel();
        lblCapacidade = new javax.swing.JLabel();
        txtCodigoSala = new javax.swing.JTextField();
        txtNomeSala = new javax.swing.JTextField();
        txtCapacidade = new javax.swing.JTextField();
        lblSalaAdaptada = new javax.swing.JLabel();
        txtSalaAdaptada = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSala = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Salas");
        setResizable(false);

        lblCodigoSala.setText("Codigo Sala:");

        lblNomeSala.setText("Nome Sala:");

        lblCapacidade.setText("Capacidade:");

        txtCodigoSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoSalaActionPerformed(evt);
            }
        });

        txtNomeSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeSalaActionPerformed(evt);
            }
        });

        txtCapacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadeActionPerformed(evt);
            }
        });

        lblSalaAdaptada.setText("Sala Adaptada:");

        txtSalaAdaptada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaAdaptadaActionPerformed(evt);
            }
        });

        tblSala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSala.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblSalaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblSala);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoSala)
                            .addComponent(lblCapacidade)
                            .addComponent(lblNomeSala)
                            .addComponent(lblSalaAdaptada))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeSala, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSalaAdaptada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                .addComponent(txtCapacidade, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoSala)
                    .addComponent(txtCodigoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeSala)
                    .addComponent(txtNomeSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapacidade)
                    .addComponent(txtCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalaAdaptada)
                    .addComponent(txtSalaAdaptada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static synchronized SalaUI getInstance(){
        if(salaInstancia == null){
            salaInstancia = new SalaUI();
        }
        
        // Abre janela centralizada.
        salaInstancia.setLocationRelativeTo(null);
        
        return salaInstancia;
    }
    
    private void txtCapacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadeActionPerformed

    private void txtCodigoSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoSalaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int codigo = Integer.parseInt(txtCodigoSala.getText());
        SalaCL.deleteSala(codigo);
        retrieveSala();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        int     cod = Integer.parseInt(txtCodigoSala.getText());
//        double  rend = Double.parseDouble(txtRenda.getText());
        String  nom = txtNomeSala.getText();
        
        if(nom != null){
            SalaBO c = SalaCL.findSalaNome(nom);
            findSala(c);
        }else if(String.valueOf(cod) != null){
            
            String str = String.valueOf(cod);
            // suppose str becomes null after some operation(s).
            int number = 0;
            try
            {
                if(str != null)
                  number = Integer.parseInt(str);
            }
            catch (NumberFormatException e)
            {
                number = 0;
            }            
            
            SalaBO c = SalaCL.findSalaCod(number);
            findSala(c);
        }else{
            JOptionPane.showMessageDialog(null,"Digite um parâmetro válido!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        SalaBO Sala = readSala();
        SalaCL.updateSala(Sala);
        JOptionPane.showMessageDialog(null,"Sala atualizado com sucesso!");
        retrieveSala();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        SalaBO sala = readSala();
        SalaCL.newSala(sala);
        JOptionPane.showMessageDialog(null,"Sala cadastrado com sucesso!");
        retrieveSala();    

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tblSalaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblSalaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSalaAncestorAdded

    private void txtSalaAdaptadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaAdaptadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaAdaptadaActionPerformed

    private void txtNomeSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaUI().setVisible(true);
            }
        });
    }
    
    
    public SalaBO readSala(){
        int codigoSala = Integer.parseInt(txtCodigoSala.getText());
        String nomeSala = txtNomeSala.getText();
        int capacidade = Integer.parseInt(txtCapacidade.getText());
        String adaptada = txtSalaAdaptada.getText();
                   
        return new SalaBO(codigoSala, nomeSala,capacidade, adaptada);    
    }    

    public void findSala(SalaBO c){
        txtCodigoSala.setText(String.valueOf(c.getCodigoSala()));
        txtNomeSala.setText(c.getNomeSala());
        txtCapacidade.setText(String.valueOf(c.getCapacidade()));  
        txtSalaAdaptada.setText(c.getAdaptada()); 
              
    }  
    
    public void retrieveSala(){
            
        DefaultTableModel modelinho = new DefaultTableModel();
        modelinho.addColumn("Codigo Sala");
        modelinho.addColumn("Nome Sala:");
        modelinho.addColumn("Capacidade");
        modelinho.addColumn("Adaptada");
        tblSala.setModel(modelinho);
            
        SalaCL.showSala().stream().forEach((SalaBO s) -> {
            modelinho.addRow(new Object[]{
                s.getCodigoSala(), 
                s.getNomeSala(),
                s.getCapacidade(), 
                s.getAdaptada()
            });
        });
        
        tblSala.setModel(modelinho);
    }
    //nt codigoSala,String nomeSala, int capacidade, boolean adaptada
    private void writeSala(SalaBO c){
        txtCodigoSala.setText(String.valueOf(c.getCodigoSala()));
        txtNomeSala.setText(c.getNomeSala());
        txtCapacidade.setText(String.valueOf(c.getCapacidade()));  
        txtSalaAdaptada.setText(c.getAdaptada());  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCapacidade;
    private javax.swing.JLabel lblCodigoSala;
    private javax.swing.JLabel lblNomeSala;
    private javax.swing.JLabel lblSalaAdaptada;
    private javax.swing.JTable tblSala;
    private javax.swing.JTextField txtCapacidade;
    private javax.swing.JTextField txtCodigoSala;
    private javax.swing.JTextField txtNomeSala;
    private javax.swing.JTextField txtSalaAdaptada;
    // End of variables declaration//GEN-END:variables
}
